### PR TITLE
Generation of training data for tables and figures outputs less element than in input 

### LINKED ISSUE #693: Create training - missing figure/table training data as compared with the upstream model (fulltext)
I'm working on adding some more training data, at the moment I'm focusing on fulltext and segmentation, however I'm targerting figures and tables segmentation as well. 

[PR05514733-CC.pdf](https://github.com/kermitt2/grobid/files/5811918/PR05514733-CC.pdf)

In this case, although the fulltext is correctly recognising the figures, there is no training data for the figure model in output. 

I've started digging and it seems a problem coming from `FulltextParser.processTrainingDataFigures`, where if there is only one figure (one I-<figure>) the content seems just ignored. 
I was going to try to fix it, but i'm afraid I'm going to break something else. I've created a draft PR #694. 

Here a test that tries to reproduce the problem: 

```java
        String text = "The mechanism for superconductivity FIG. 1. λ(T) vs . T for YBCO";
        List<LayoutToken> tokens = GrobidAnalyzer.getInstance().tokenizeWithLayoutToken(text);
        String rese = "The\tthe\tT\tTh\tThe\tThe\te\the\tThe\tThe\tBLOCKSTART\tLINESTART\tALIGNEDLEFT\tNEWFONT\tHIGHERFONT\t0\t0\tINITCAP\tNODIGIT\t0\tNOPUNCT\t0\t4\t0\tNUMBER\t0\t0\tI-<paragraph>\n" +
            "mechanism\tmechanism\tm\tme\tmec\tmech\tm\tsm\tism\tnism\tBLOCKIN\tLINEIN\tALIGNEDLEFT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tNOCAPS\tNODIGIT\t0\tNOPUNCT\t0\t4\t0\tNUMBER\t0\t0\t<paragraph>\n" +
            "for\tfor\tf\tfo\tfor\tfor\tr\tor\tfor\tfor\tBLOCKIN\tLINEIN\tALIGNEDLEFT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tNOCAPS\tNODIGIT\t0\tNOPUNCT\t0\t4\t0\tNUMBER\t0\t0\t<paragraph>\n" +
            "superconductivity\tsuperconductivity\ts\tsu\tsup\tsupe\ty\tty\tity\tvity\tBLOCKIN\tLINEIN\tALIGNEDLEFT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tNOCAPS\tNODIGIT\t0\tNOPUNCT\t0\t4\t0\tNUMBER\t0\t0\t<paragraph>" +
            "FIG\tfig\tF\tFI\tFIG\tFIG\tG\tIG\tFIG\tFIG\tBLOCKSTART\tLINESTART\tLINEINDENT\tNEWFONT\tHIGHERFONT\t0\t0\tALLCAP\tNODIGIT\t0\tNOPUNCT\t10\t3\t0\tNUMBER\t0\t0\tI-<figure>\n" +
            ".\t.\t.\t.\t.\t.\t.\t.\t.\t.\tBLOCKIN\tLINEIN\tLINEINDENT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tALLCAP\tNODIGIT\t1\tDOT\t10\t3\t0\tNUMBER\t0\t0\t<figure>\n" +
            "1\t1\t1\t1\t1\t1\t1\t1\t1\t1\tBLOCKIN\tLINEIN\tLINEINDENT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tNOCAPS\tALLDIGIT\t1\tNOPUNCT\t10\t3\t0\tNUMBER\t1\t0\t<figure>\n" +
            ".\t.\t.\t.\t.\t.\t.\t.\t.\t.\tBLOCKIN\tLINEIN\tLINEINDENT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tALLCAP\tNODIGIT\t1\tDOT\t10\t3\t0\tNUMBER\t0\t0\t<figure>\n" +
            "λ\tλ\tλ\tλ\tλ\tλ\tλ\tλ\tλ\tλ\tBLOCKIN\tLINEIN\tLINEINDENT\tNEWFONT\tSAMEFONTSIZE\t0\t0\tNOCAPS\tNODIGIT\t1\tNOPUNCT\t10\t3\t0\tNUMBER\t0\t0\t<figure>\n" +
            "(\t(\t(\t(\t(\t(\t(\t(\t(\t(\tBLOCKIN\tLINEIN\tLINEINDENT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tALLCAP\tNODIGIT\t1\tOPENBRACKET\t10\t3\t0\tNUMBER\t0\t0\t<figure>\n" +
            "T\tt\tT\tT\tT\tT\tT\tT\tT\tT\tBLOCKIN\tLINEIN\tLINEINDENT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tALLCAP\tNODIGIT\t1\tNOPUNCT\t10\t3\t0\tNUMBER\t0\t0\t<figure>\n" +
            ")\t)\t)\t)\t)\t)\t)\t)\t)\t)\tBLOCKIN\tLINEIN\tLINEINDENT\tNEWFONT\tSAMEFONTSIZE\t0\t0\tALLCAP\tNODIGIT\t1\tENDBRACKET\t10\t3\t0\tNUMBER\t0\t0\t<figure>\n" +
            "vs\tvs\tv\tvs\tvs\tvs\ts\tvs\tvs\tvs\tBLOCKIN\tLINEIN\tLINEINDENT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tNOCAPS\tNODIGIT\t0\tNOPUNCT\t10\t3\t0\tNUMBER\t0\t0\tI-<figure>\n" +
            ".\t.\t.\t.\t.\t.\t.\t.\t.\t.\tBLOCKIN\tLINEEND\tLINEINDENT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tALLCAP\tNODIGIT\t1\tDOT\t10\t3\t0\tNUMBER\t0\t0\t<figure>\n" +
            "T\tt\tT\tT\tT\tT\tT\tT\tT\tT\tBLOCKIN\tLINESTART\tLINEINDENT\tNEWFONT\tSAMEFONTSIZE\t0\t0\tALLCAP\tNODIGIT\t1\tNOPUNCT\t10\t3\t0\tNUMBER\t0\t0\t<figure>\n" +
            "for\tfor\tf\tfo\tfor\tfor\tr\tor\tfor\tfor\tBLOCKIN\tLINEIN\tLINEINDENT\tNEWFONT\tSAMEFONTSIZE\t0\t0\tNOCAPS\tNODIGIT\t0\tNOPUNCT\t10\t3\t0\tNUMBER\t0\t0\t<figure>\n" +
            "YBCO\tybco\tY\tYB\tYBC\tYBCO\tO\tCO\tBCO\tYBCO\tBLOCKIN\tLINEIN\tLINEINDENT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tALLCAP\tNODIGIT\t0\tNOPUNCT\t10\t3\t0\tNUMBER\t0\t0\t<figure>";


        Pair<String, String> stringStringPair = target.processTrainingDataFigures(rese, tokens, "123");

        System.out.println(stringStringPair.getLeft());
        System.out.println(stringStringPair.getRight());
```

And the result is quite strange:
1. if  there is only one `<figure>` block (e.g. line `"vs\tvs\tv\tvs\tvs\tvs\ts\tvs\tvs\tvs\tBLOCKIN\tLINEIN\tLINEINDENT\tSAMEFONT\tSAMEFONTSIZE\t0\t0\tNOCAPS\tNODIGIT\t0\tNOPUNCT\t10\t3\t0\tNUMBER\t0\t0\t<figure>\n" +` (does not have the `I-` prefix in the label, the output is empty, 
2. if there are two `<figure>` blocks, then the output is: 

```
<tei>
    <teiHeader>
        <fileDesc xml:id="_123"/>
    </teiHeader>
    <text xml:lang="en">


        <figure>

            <figDesc>superconductivity . 1. λ(T)</figDesc>
        </figure>



    </text>
</tei>

superconductivity	superconductivity	s	su	sup	supe	y	ty	ity	vity	BLOCKIN	LINEIN	ALIGNEDLEFT	SAMEFONT	SAMEFONTSIZE	0	0	NOCAPS	NODIGIT	0	NOPUNCT	0	4	0	NUMBER	0	0	<paragraph>FIG	fig	F	FI	FIG	FIG	G	IG	FIG	FIG	BLOCKSTART	LINESTART	LINEINDENT	NEWFONT	HIGHERFONT	0	0	ALLCAP	NODIGIT	0	NOPUNCT	10	3	0	NUMBER	0	0
.	.	.	.	.	.	.	.	.	.	BLOCKIN	LINEIN	LINEINDENT	SAMEFONT	SAMEFONTSIZE	0	0	ALLCAP	NODIGIT	1	DOT	10	3	0	NUMBER	0	0
1	1	1	1	1	1	1	1	1	1	BLOCKIN	LINEIN	LINEINDENT	SAMEFONT	SAMEFONTSIZE	0	0	NOCAPS	ALLDIGIT	1	NOPUNCT	10	3	0	NUMBER	1	0
.	.	.	.	.	.	.	.	.	.	BLOCKIN	LINEIN	LINEINDENT	SAMEFONT	SAMEFONTSIZE	0	0	ALLCAP	NODIGIT	1	DOT	10	3	0	NUMBER	0	0
λ	λ	λ	λ	λ	λ	λ	λ	λ	λ	BLOCKIN	LINEIN	LINEINDENT	NEWFONT	SAMEFONTSIZE	0	0	NOCAPS	NODIGIT	1	NOPUNCT	10	3	0	NUMBER	0	0
(	(	(	(	(	(	(	(	(	(	BLOCKIN	LINEIN	LINEINDENT	SAMEFONT	SAMEFONTSIZE	0	0	ALLCAP	NODIGIT	1	OPENBRACKET	10	3	0	NUMBER	0	0
T	t	T	T	T	T	T	T	T	T	BLOCKIN	LINEIN	LINEINDENT	SAMEFONT	SAMEFONTSIZE	0	0	ALLCAP	NODIGIT	1	NOPUNCT	10	3	0	NUMBER	0	0
)	)	)	)	)	)	)	)	)	)	BLOCKIN	LINEIN	LINEINDENT	NEWFONT	SAMEFONTSIZE	0	0	ALLCAP	NODIGIT	1	ENDBRACKET	10	3	0	NUMBER	0	0

```

which does not look correct. Could be that I did not re-create a real case (I took an excerprt from the figure in the pdf I'm attaching).

### PR DESCRIPTION
**Pull request by lfoppiano**
Attempt to fix #693, and is valid for both figures and tables.
One case is when only one figure/table is identified in the fulltext, it is not output in the respective training data.

The fix attempt to verify that there are not figure/tables accumulated but not consumed

To reproduce the behaviour as explained in #693 is necessary to merge here the `features/add-training-data` or use the branch `bugfix/fix-figure-table-training-data-generation`

### CODE REVIEW

File: grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java [hunk 1]
```diff
@@ -2032,16 +2029,35 @@ else if (label.equals("I-<figure>") || openFigure) {
...
+    	if (openFigure) {
+            while((tokenizationsFigure.size() > 0) &&
+                (tokenizationsFigure.get(0).getText().equals("\n") ||
+                    tokenizationsFigure.get(0).getText().equals(" ")) )
+                tokenizationsFigure.remove(0);
+
+            // process the "accumulated" figure
+            Pair<String,String> trainingData = parsers.getFigureParser()
+                .createTrainingData(tokenizationsFigure, figureBlock.toString(), "Fig" + nb);
+            if (trainingData!= null) {
```
Comment (de-code) [inline grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java:2050]: Might be worth extracting into a shared method?

Do you know under what circumstances `trainingData` would be `null`?

**Comment by de-code** [comment]
Looking good to me. Just minor comment regarding extracting function.

I haven't run it myself yet. From the code I read that the issue was that if the `figure` or `table` is the last "item" of the `fulltext` model, then it was omitted from the output?

**Review by de-code — APPROVED** [review]

**Comment by lfoppiano** [comment]
> Looking good to me. Just minor comment regarding extracting function.

Thanks! 

> I haven't run it myself yet. From the code I read that the issue was that if the `figure` or `table` is the last "item" of the `fulltext` model, then it was omitted from the output?

yes, the last item or the only item.
